# Assignment 3: ICP + Non-linear least squares optimization

TEAM-NAME: Bhagwaan Bharose

YOUR-ID: 

YOUR-NAME: Tushar Choudhary

## Instructions

* You are not allowed to use any external libraries (other than ones being imported below).
* The deadline for this assignment is **15-09-21** at 11:55pm.
* Plagiarism is **strictly prohibited**

In [1]:
import math
import numpy as np
import matplotlib.pyplot as plt

# Non Linear Least Squares Optimization

## 1.1 Gradient Descent
Implement the gradient descent algorithm using numpy and what you have learned from class to solve for the parameters of a gaussian distribution.
To understand the task in more detail and look at a worked through example, checkout the subsequent section. You have to implement the same using just numpy functions. You can refer to [Shubodh's notes](https://www.notion.so/saishubodh/From-linear-algebra-to-non-linear-weighted-least-squares-optimization-13cf17d318be4d45bb8577c4d3ea4a02) on the same to get a better grasp of the concept before implementing it.
* Experiment with the number of iterations.
* Experiment with the learning rate.
* Experiment with the tolerance.

Display your results using matplotlib by plotting graphs for 
* The cost function value vs the number of iterations
* The Ground Truth data values and the predicted data values.

Your plots are expected to contain information similar to the plot below:

<!-- <figure> -->
<img src='./helpers/sample_plt.png' alt=drawing width=500 height=600>

<!-- <figcaption align='center'><b>A sample plot, you can use your own plotting template</b></figcaption>
</figure> -->
<!-- head over to [this page](https://saishubodh.notion.site/Non-Linear-Least-Squares-Solved-example-Computing-Jacobian-for-a-Gaussian-Gradient-Descent-7fd11ebfee034f8ca89cc78c8f1d24d9) -->

## Worked out Example using Gradient Descent

A Gaussian distribution parametrized by $a,m,s$ is given by:

$$ y(x;a,m,s)=a \exp \left(\frac{-(x-m)^{2}}{2 s^{2}}\right) \tag{1}$$

### Jacobian of Gaussian

$$\mathbf{J}_y=\left[\frac{\partial y}{\partial a} \quad \frac{\partial y}{\partial m} \quad \frac{\partial y}{\partial s}\right] \\
= \left[ \exp \left(\frac{-(x-m)^{2}}{2 s^{2}}\right); \frac{a (x-m)}{s^2} \exp\left(\frac{-(x-m)^{2}}{2 s^{2}}\right);  \frac{a (x-m)^2}{s^3}\exp \left(\frac{-(x-m)^{2}}{2 s^{2}}\right)\right]$$

## Problem at hand

> Given a set of observations $y_{obs}$ and $x_{obs}$ we want to find the optimum parameters $a,m,s$ which best fit our observations given an initial estimate.

Our observations would generally be erroneous and given to us, but for the sake of knowing how good our model is performing, let us generate the observations ourselves by assuming the actual "actual" parameter values as $a_{gt}=10; m_{gt} =0; s_{gt} =20$ ($gt$ stands for ground truth). We will try to estimate these values based on our observations and let us see how close we get to "actual" parameters. Note that in reality we obviously don't have these parameters as that is exactly what we want to estimate in the first place. So let us consider the following setup, we have:

- Number of observations, $num\_obs = 50$
- Our 50 set of observations would be
    - $x_{obs} = np.linspace(-25,25, num\_obs)$
    - $y_{obs} = y(x_{obs};a_{gt},m_{gt},s_{gt})$  from $(1)$

Reference:

→[linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

- Say we are given initial estimate as:

    $$a_0=10; \quad m_0=13; \quad s_0=19.12$$

### Residual and error to be minimized

Okay, now we have set of observations and an initial estimate of parameters. We would now want to minimize an error that would give us optimum parameters.

The $residual$ would be given by

$$ r(a,m,s) = \left[ a \exp \left(\frac{-(x_{obs}-m)^{2}}{2 s^{2}}\right) - y_{obs}\ \right]$$

where we'd want to minimize $\|r\|^2$. Note that $r$ is a non-linear function in $(a,m,s)$.

Also, note that since $y$ (and $x$) are observations in the above equation, after simplification, we get $\mathbf{J}_r = \mathbf{J}_y$ [above](https://www.notion.so/c9e6f71b67a44bb8b366df2fccfc12d0) (since $y_{obs}$ is a constant).

Let us apply Gradient Descent method for minimization here. From [Table I](https://www.notion.so/From-linear-algebra-to-non-linear-weighted-least-squares-optimization-13cf17d318be4d45bb8577c4d3ea4a02),  

$$\Delta \mathbf{k} = - \alpha \mathbf{J_F} = -\alpha \mathbf{J}_r^{\top} {r}(\mathbf{k})$$

Note that $\mathbf{J_F}$ is the Jacobian of "non-linear least squares" function $\mathbf{F}$ while $\mathbf{J}_r$ is the Jacobian of the residual. 

where $\mathbf{k}$ is $[a,m,s]^T$. 

- Some hyperparameters:
    - Learning rate, $lr = 0.01$
    - Maximum number of iterations, $num\_iter=200$
    - Tolerance, $tol = 1e-15$

## Solution for 1 iteration

To see how each step looks like, let us solve for 1 iteration and for simpler calculations, assume we have 3 observations, 

$$x_{obs}= \left[ -25, 0, 25 \right]^T, y_{obs} = \left[  4.5783, 10, 4.5783 \right]^T. $$

With our initial estimate as $\mathbf{k_0} = [a_0=10, \quad m_0=13, \quad s_0=19.12]^T$, the residual would be 

$$ r(a_0,m_0,s_0) = \left[ a_0 \exp \left(\frac{-(x_{obs}-m_0)^{2}}{2 s_0^{2}}\right) - y_{obs}\ \right]$$

Therefore, $r=[-3.19068466, -2.0637411 , 3.63398058]^T$.

### Gradient Computation

Gradient, $\mathbf{J_F}$=

$$\mathbf{J_r}^{\top} \mathbf{r}(\mathbf{k})$$

We have calculated residual already [above](https://www.notion.so/c9e6f71b67a44bb8b366df2fccfc12d0), let us calculate the Jacobian $\mathbf{J_r}$.

$$\mathbf{J}_r
= \left[ \exp \left(\frac{-(x-m)^{2}}{2 s^{2}}\right); \frac{a (x-m)}{s^2} \exp\left(\frac{-(x-m)^{2}}{2 s^{2}}\right);  \frac{a (x-m)^2}{s^3}\exp \left(\frac{-(x-m)^{2}}{2 s^{2}}\right)\right]$$

$$\implies \mathbf{J_r} = \left[ \begin{array}{rrr}0.1387649 & 0.79362589, & 0.82123142 \\-0.14424057 & -0.28221715  & 0.26956967 \\0.28667059 & 0.19188405, & 0.16918599\end{array}\right]$$

So ,

$$\mathbf{J_F} = \mathbf{J_r}^{\top} \mathbf{r}(\mathbf{k})$$

$$\mathbf{r}(\mathbf{k}) =  \left[ \begin{array}{r}-3.19068466 \\ -2.0637411 \\ 3.63398058 \end{array} \right]$$

$$ \begin{aligned} \implies \mathbf{J_F} = \left[ \begin{array}{r} 0.89667553 \\ -1.25248392 \\-2.56179392\end{array} \right] \end{aligned}$$

### Update step

$$
\Delta \mathbf{k} = - \alpha \mathbf{J_F} \\
\mathbf{k}^{t+1} = \mathbf{k}^t + \Delta \mathbf{k}
$$

Here, $\alpha$ our learning rate is 0.01.

$$
\Delta \mathbf{k} = - \alpha\times\left[ \begin{array}{r} 
0.89667553 \\ -1.25248392 \\-2.56179392
\end{array} \right] = \left[ \begin{array}{r}
-0.00896676 \\ 0.01252484 \\0.02561794
\end{array}\right]
$$

$$
\mathbf{k}^{1} = \mathbf{k}^{0} + \Delta \mathbf{k} \\ \left[\begin{array}{r} 10 \\ 13 \\ 19.12 \end{array}\right] + \left[\begin{array}{c} 9.99103324 \\ 13.01252484 \\ 19.14561794 \end{array} \right]
$$

With just one iteration with very few observations, we can see that we have gotten *slightly* more closer to our GT parameter  $a_{gt}=10; m_{gt} =0; s_{gt} =20$. Our initial estimate was $[a_0=10, \quad m_0=13, \quad s_0=19.12]$. However, the above might not be noticeable enough: Hence you need to code it for more iterations and convince yourself as follows:

In [2]:
from helpers.func import make_gaussian

## 1.2: Another Non-Linear function
Now that you've got the hang of computing the jacobian matrix for a non-linear function via the aid of an example, try to compute the jacobian of a secondary gaussian function by carrying out steps similar to what has been shown above. The function is plotted below:
<img src='./helpers/non_linear.png' alt=drawing width=500 height=600>
Using the computed jacobian, optimise for the four parameters using gradient descent, where the parameters to be estimated are: 

$p_1$ = 2,  $p_2$ = 8,  $p_3$ = 4,  $p_4$ = 8. 

Do this for $x_{obs} = np.linspace(-20,30, num\_obs)$,
where $num\_obs$ is 50.



In [ ]:
from helpers.func import make_non_linear

## 1.3: Different Optimizers

Replace gradient descent with Gauss-Newton and Levenberg Marquardt algorithms and repeat question 1.1. 

To quickly recap, Gauss-Newton and Levenberg Marquardt are alternate update rules to the standard gradient descent. Gauss Newton updates work as:

$$\delta x = -(J^TJ)^{-1}J^Tf(x)$$

Levenberg Marquardt lies somewhere between Gauss Newton and Gradient Descent algorithms by blending the two formulations. As a result, when at a steep cliff, LM takes small steps to avoid overshooting, and when at a gentle slope, LM takes bigger steps:


$$\delta x = -(J^TJ + \lambda I)^{-1}J^Tf(x)$$

**Questions**
   * 1. How does the choice of initial estimate and learning rate affect convergence? Observations and analysis from repeated runs with modified hyperparameters will suffice.
   * 2. Do you notice any difference between the three optimizers? Why do you think that is? (If you are unable to see a clear trend, what would you expect in general based on what you know about them)

# 2. Iterative Closest Point

In this subsection, we will code the Iterative Closest Point algorithm to find the alignment between two point clouds without known correspondences. The point cloud that you will be using is the same as the one that you used in Assignment 1.

## 2.1: Procrustes alignment

1. Write a function that takes two point clouds as input wherein the corresponding points between the two point clouds are located at the same index and returns the transformation matrix between them.
2. Use the bunny point cloud and perform the procrustes alignment between the two bunnies. Compute the absolute alignment error after aligning the two bunnies.
3. Make sure your code is modular as we will use this function in the next sub-part.
4. Prove mathematically why the Procrustes alignment gives the best aligning transform between point clouds with known correspondences.


In [3]:
import numpy as np 
import math
import open3d as o3d

pcd = o3d.io.read_point_cloud("./bunny.pcd")
out_arr = np.asarray(pcd.points)  
print ("output array from input list : ", out_arr) 
out_arr = out_arr.T
out_arr.shape
X = out_arr
P = X + 0.05 * np.random.normal(0, 1, X.shape)
  
# translate
P[0,:] = P[0,:] + 100
P[1,:] = P[1,:] + 100
P[2,:] = P[2,:] + 100

# rotate
theta1 = ( 180.0 / 360) * 2 * np.pi
rot1 = np.array([[math.cos(theta1), -math.sin(theta1),0],
                 [math.sin(theta1),  math.cos(theta1),0],
               [0,0,1]])



P1 = np.dot(rot1, P)

print(P1)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
output array from input list :  [[ 2.97875684e-02 -1.26088396e-01  5.66354059e-02]
 [ 2.57391799e-02 -1.25391304e-01  4.62108552e-02]
 [ 5.48149124e-02 -1.80901647e-01  1.13657052e-02]
 ...
 [-4.94631976e-02 -1.19555235e-01  7.69835478e-03]
 [ 2.73076512e-05 -1.53572425e-01  6.68406561e-02]
 [-5.89424884e-03 -1.49966553e-01  5.33136539e-02]]
[[ -99.96377029 -100.105769   -100.08977342 ...  -99.90486147
  -100.02821494  -99.92242593]
 [ -99.8487668   -99.89663804  -99.82465182 ...  -99.88818733
   -99.90070578  -99.81196305]
 [  99.96138596  100.06135814  100.06886634 ...   99.96728222
   100.08700519  100.12808715]]


In [211]:
def ICP(X, P):
    num_iter = 100 
    P0 = P  
    n = X.shape[1]
    dim = X.shape[0]
    
    for i in range(num_iter):

        error = np.sqrt(np.sum(np.square(X-P)) / X.shape[1])
        print(error)
        

        mean_pc1 = np.mean(X, axis = 1, keepdims = True)
        mean_pc2 = np.mean(P, axis = 1, keepdims = True)

        W = np.zeros((3,3))

        for ind in range(n):
            pc1 = X[:, ind]
            pc1 = pc1.reshape(3,1)
            arr1 = pc1 - mean_pc1
            pc2 = P[:, ind]
            pc2 = pc2.reshape(3,1)
            arr2 = pc2 - mean_pc2
            W = W+np.dot(arr1,arr2.T)

        W = W/n
        
        U, S, Vt = np.linalg.svd(W)
        
        # Rotation matrix
        R = np.dot(U,Vt)
#         print(np.linalg.det(R))
        if np.linalg.det(R) < 0:
            print("lol")
            Vt[dim - 1, :]*=-1
            R = U @ Vt
        # Translation matrix
        t = mean_pc1 - np.dot( R , mean_pc2)
        
        P = np.dot(R, P) + t #Uncomment this: transforming my current point cloud towards initial point cloud

    return R , t

In [212]:
ICP(X,P1)

173.24589651755127
lol
0.8232515335966442
0.823251533596644
0.823251533596644
0.823251533596644
0.823251533596644
0.8232515335966442
0.8232515335966442
0.823251533596644
0.8232515335966439
0.8232515335966439
0.823251533596644
0.823251533596644
0.8232515335966443
0.8232515335966443
0.8232515335966444
0.8232515335966445
0.8232515335966446
0.8232515335966447
0.8232515335966448
0.8232515335966448
0.8232515335966448
0.8232515335966449
0.8232515335966449
0.8232515335966448
0.8232515335966447
0.8232515335966446
0.8232515335966447
0.8232515335966448
0.8232515335966448
0.8232515335966448
0.8232515335966448
0.8232515335966446
0.8232515335966447
0.8232515335966447
0.8232515335966447
0.8232515335966447
0.8232515335966448
0.8232515335966448
0.8232515335966449
0.823251533596645
0.823251533596645
0.823251533596645
0.8232515335966449
0.8232515335966449
0.8232515335966448
0.8232515335966447
0.8232515335966447
0.8232515335966446
0.8232515335966446
0.8232515335966447
0.8232515335966446
0.8232515335966446

(array([[ 1.00000000e+00, -1.22486519e-17,  0.00000000e+00],
        [-4.72433857e-17,  1.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]),
 array([[-2.32452946e-17],
        [-2.77555756e-18],
        [-1.38777878e-18]]))

## 2.2: ICP alignment

1. Write a function that takes two point clouds as input without known correspondences and perform the iterative closest point algorithm.
2. Perform the ICP alignment between the two bunnies and plot their individual coordinate frames as done in class.
3. Does ICP always give the correct alignment? Why or Why not?
4. What are other variants of ICP and why are they helpful (you can look at point to plane ICP)?

In [34]:
# 173.1741975267442
# (array([[-0.99999421,  0.00151393,  0.00304923],
#         [-0.00153948, -0.99996356, -0.00839683],
#         [ 0.00303641, -0.00840148,  0.9999601 ]]),
#  array([[-100.15310143],
#         [ -99.30994215],
#         [-100.53168772]]))

In [ ]:
import numpy as np 
import math
import open3d as o3d

pcd = o3d.io.read_point_cloud("./bunny.pcd")
out_arr = np.asarray(pcd.points)  
# print ("output array from input list : ", out_arr) 
out_arr = out_arr.T
out_arr.shape
X = out_arr
# X = np.array([[0,1,0,-1,0],[0,0,-1,0,1],[0,0,0,0,0]])
d = np.zeros(X.shape) 
# upar wala recheck
# print(d.shape)
e = X[:,::100]
X = e
# print(e.shape) 


P = X + 0.05 * np.random.normal(0, 1, X.shape)
print(X.shape)
P = P.T

np.random.shuffle(P)
P = P.T

# translate
P[0,:] = P[0,:] + 100
P[1,:] = P[1,:] + 100
P[2,:] = P[2,:] + 100

# rotate
theta1 = ( 180.0 / 360) * 2 * np.pi
rot1 = np.array([[math.cos(theta1), -math.sin(theta1),0],
                 [math.sin(theta1),  math.cos(theta1),0],
               [0,0,1]])



P1 = np.dot(rot1, P)

# print(P1)

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(X.T)
# o3d.visualization.draw_geometries([pcd])


pcd.estimate_normals()

distances = pcd.compute_nearest_neighbor_distance()
avg_dist = np.mean(distances)
radius = 1.5 * avg_dist   

mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(
           pcd,
           o3d.utility.DoubleVector([radius, radius * 2]))
o3d.visualization.draw_geometries([mesh])



(3, 35947)


In [264]:

def nearest_neighbour(X,P):
#     print("started")
    corres = []
    n = P.shape[1]    
    for ind in range(n):
        pc1 = P[:, ind]
        pc1 = pc1.reshape(3,1) 
        dist = 9999999999999 
        idx = -1
        for i in range(n):           
            pc2 = X[:, i]
            pc2 = pc2.reshape(3,1)
            if np.sum(np.square(pc1-pc2)) < dist:
                dist = np.sum(np.square(pc1-pc2))
                idx = i
        corres.append(idx)
#         print(ind)
#     print("ended")
#     print("printed from func ", corres)
    return corres
           

        
        
    

In [265]:
def ICP(X, P):
    num_iter = 5000
    P0 = P  
    n = X.shape[1]
    dim = X.shape[0]
    
    
    for i in range(num_iter):
#         np.random.shuffle(P)
#         np.random.shuffle(np.transpose(P))

        error = np.sqrt(np.sum(np.square(X-P)) / X.shape[1])
        print(error)
        

        mean_pc1 = np.mean(X, axis = 1, keepdims = True)
        mean_pc2 = np.mean(P, axis = 1, keepdims = True)

        W = np.zeros((3,3))
        cor = nearest_neighbour(X, P)
        cor = np.array(cor)
        cor  = cor.astype(int)
#         print(cor)
        for ind in range(n):
            pc1 = X[:, cor[ind]]
            pc1 = pc1.reshape(3,1)
            arr1 = pc1 - mean_pc1
            pc2 = P[:, ind]
            pc2 = pc2.reshape(3,1)
            arr2 = pc2 - mean_pc2
            W = W+np.dot(arr1,arr2.T)

        W = W/n
    
        
        U, S, Vt = np.linalg.svd(W)
        
        # Rotation matrix
        R = np.dot(U,Vt)
        if np.linalg.det(R) < 0:
#             print("lol")
            Vt[dim - 1, :]*=-1
            R = U @ Vt
        # Translation matrix
        t = mean_pc1 - np.dot( R , mean_pc2)
#         print(t , R)
        
        P = np.dot(R, P) + t #Uncomment this: transforming my current point cloud towards initial point cloud

    return cor , P

In [266]:
ICP(X,P1)
# print(X,P1)
# print(X)

173.17073458053386
0.16458208457527976
0.16449331164661535
0.1644185519518773
0.16436813378201268
0.16433520203147942
0.16430336686404134
0.16428646300699565
0.16427038598280314
0.16425255659634388
0.16424106461525045
0.16422596922866423
0.16420519299061714
0.16419125402041101
0.16417505514042904
0.16416719861555737
0.16417366039474332
0.16418053922407963
0.16418061812861218
0.16419140418147382
0.16419689988510694
0.16419689988510697
0.16419689988510694
0.16419689988510694
0.16419689988510697
0.16419689988510694
0.16419689988510694
0.16419689988510694
0.16419689988510702
0.16419689988510705
0.16419689988510705
0.16419689988510702
0.16419689988510702
0.16419689988510705
0.16419689988510702
0.16419689988510702
0.16419689988510702
0.16419689988510705
0.16419689988510708
0.16419689988510708
0.16419689988510708
0.16419689988510708
0.16419689988510708
0.16419689988510705
0.16419689988510702
0.16419689988510705
0.16419689988510705
0.16419689988510705
0.16419689988510705
0.16419689988510708
0.

0.1641968998851101
0.1641968998851101
0.1641968998851101
0.16419689988511008
0.1641968998851101
0.16419689988511013
0.1641968998851101
0.16419689988511008
0.16419689988511008
0.16419689988511008
0.1641968998851101
0.16419689988511008
0.1641968998851101
0.16419689988511008
0.1641968998851101
0.16419689988511008
0.16419689988511008
0.16419689988511008
0.16419689988511005
0.16419689988511002
0.16419689988511
0.16419689988511002
0.16419689988511
0.16419689988511
0.16419689988511
0.16419689988511
0.16419689988511
0.16419689988511002
0.16419689988511002
0.16419689988511002
0.16419689988511002
0.16419689988511005
0.16419689988511005
0.16419689988511005
0.16419689988511008
0.16419689988511008
0.16419689988511008
0.16419689988511008
0.1641968998851101
0.1641968998851101
0.1641968998851101
0.16419689988511013
0.16419689988511013
0.16419689988511016
0.16419689988511016
0.16419689988511016
0.16419689988511016
0.16419689988511016
0.1641968998851102
0.16419689988511016
0.16419689988511016
0.16419689

0.16419689988511077
0.16419689988511074
0.1641968998851107
0.1641968998851107
0.16419689988511066
0.16419689988511066
0.16419689988511058
0.16419689988511058
0.16419689988511052
0.16419689988511055
0.16419689988511058
0.16419689988511055
0.16419689988511052
0.1641968998851105
0.16419689988511046
0.16419689988511044
0.16419689988511038
0.16419689988511035
0.1641968998851103
0.16419689988511024
0.16419689988511021
0.1641968998851102
0.16419689988511016
0.1641968998851101
0.16419689988511008
0.16419689988511005
0.16419689988511002
0.16419689988511
0.16419689988511002
0.16419689988510996
0.16419689988511
0.16419689988510996
0.16419689988510994
0.16419689988510994
0.16419689988510988
0.1641968998851098
0.16419689988510977
0.16419689988510972
0.1641968998851097
0.16419689988510966
0.16419689988510966
0.16419689988510963
0.1641968998851096
0.16419689988510958
0.16419689988510955
0.1641968998851095
0.1641968998851095
0.1641968998851095
0.16419689988510947
0.16419689988510944
0.1641968998851094

0.16419689988510375
0.16419689988510378
0.16419689988510383
0.16419689988510383
0.1641968998851039
0.16419689988510391
0.16419689988510391
0.1641968998851039
0.1641968998851039
0.16419689988510386
0.1641968998851039
0.1641968998851039
0.16419689988510391
0.16419689988510394
0.16419689988510397
0.16419689988510394
0.16419689988510394
0.16419689988510391
0.1641968998851039
0.1641968998851039
0.16419689988510391
0.1641968998851039
0.1641968998851039
0.16419689988510391
0.16419689988510391
0.16419689988510391
0.16419689988510391
0.16419689988510394
0.16419689988510391
0.16419689988510394
0.16419689988510397
0.16419689988510397
0.16419689988510403
0.16419689988510403
0.164196899885104
0.164196899885104
0.16419689988510397
0.16419689988510391
0.16419689988510386
0.16419689988510386
0.16419689988510383
0.16419689988510386
0.16419689988510386
0.16419689988510383
0.16419689988510383
0.1641968998851039
0.16419689988510386
0.16419689988510391
0.16419689988510391
0.16419689988510394
0.164196899885

0.16419689988510755
0.16419689988510755
0.16419689988510755
0.16419689988510755
0.16419689988510755
0.16419689988510755
0.16419689988510763
0.16419689988510763
0.1641968998851077
0.1641968998851077
0.1641968998851077
0.1641968998851077
0.1641968998851077
0.16419689988510766
0.1641968998851077
0.16419689988510766
0.16419689988510766
0.16419689988510766
0.1641968998851077
0.1641968998851077
0.1641968998851077
0.16419689988510774
0.1641968998851078
0.1641968998851078
0.16419689988510783
0.16419689988510786
0.16419689988510786
0.16419689988510788
0.16419689988510786
0.16419689988510786
0.16419689988510788
0.1641968998851079
0.1641968998851079
0.16419689988510794
0.16419689988510797
0.16419689988510797
0.16419689988510794
0.164196899885108
0.164196899885108
0.16419689988510802
0.164196899885108
0.16419689988510802
0.16419689988510805
0.16419689988510805
0.16419689988510808
0.16419689988510808
0.16419689988510808
0.16419689988510808
0.16419689988510805
0.16419689988510805
0.16419689988510805

0.16419689988511021
0.16419689988511021
0.16419689988511033
0.1641968998851103
0.1641968998851103
0.1641968998851103
0.16419689988511033
0.1641968998851103
0.1641968998851103
0.16419689988511027
0.16419689988511024
0.16419689988511024
0.16419689988511024
0.16419689988511024
0.16419689988511024
0.16419689988511024
0.16419689988511021
0.16419689988511021
0.16419689988511024
0.1641968998851102
0.16419689988511021
0.1641968998851103
0.1641968998851103
0.16419689988511035
0.16419689988511035
0.16419689988511038
0.16419689988511033
0.16419689988511033
0.1641968998851103
0.16419689988511027
0.1641968998851103
0.1641968998851103
0.16419689988511033
0.1641968998851103
0.1641968998851103
0.16419689988511033
0.16419689988511035
0.1641968998851103
0.16419689988511033
0.1641968998851103
0.16419689988511033
0.16419689988511033
0.16419689988511033
0.16419689988511033
0.16419689988511033
0.1641968998851103
0.16419689988511033
0.16419689988511035
0.16419689988511033
0.16419689988511033
0.16419689988511

0.16419689988511113
0.16419689988511113
0.16419689988511119
0.16419689988511116
0.16419689988511119
0.16419689988511116
0.16419689988511116
0.16419689988511119
0.16419689988511116
0.16419689988511116
0.16419689988511113
0.16419689988511113
0.16419689988511113
0.1641968998851111
0.16419689988511113
0.1641968998851111
0.1641968998851111
0.16419689988511113
0.1641968998851111
0.16419689988511108
0.16419689988511108
0.16419689988511108
0.16419689988511108
0.16419689988511108
0.16419689988511108
0.16419689988511105
0.16419689988511108
0.16419689988511108
0.16419689988511105
0.16419689988511108
0.16419689988511105
0.16419689988511102
0.16419689988511105
0.16419689988511105
0.16419689988511105
0.16419689988511102
0.16419689988511105
0.16419689988511105
0.164196899885111
0.16419689988511102
0.164196899885111
0.164196899885111
0.16419689988511102
0.16419689988511102
0.16419689988511105
0.16419689988511105
0.16419689988511105
0.16419689988511108
0.16419689988511108
0.16419689988511113
0.16419689

0.1641968998851111
0.16419689988511108
0.16419689988511108
0.1641968998851111
0.16419689988511113
0.16419689988511116
0.16419689988511119
0.1641968998851112
0.1641968998851112
0.16419689988511119
0.1641968998851112
0.16419689988511119
0.16419689988511116
0.16419689988511119
0.16419689988511119
0.16419689988511119
0.1641968998851112
0.16419689988511119
0.16419689988511119
0.16419689988511116
0.16419689988511119
0.16419689988511119
0.1641968998851112
0.1641968998851112
0.1641968998851112
0.1641968998851112
0.1641968998851112
0.1641968998851112
0.1641968998851112
0.16419689988511119
0.16419689988511113
0.16419689988511113
0.1641968998851111
0.1641968998851111
0.16419689988511113
0.16419689988511113
0.16419689988511113
0.16419689988511113
0.1641968998851111
0.1641968998851111
0.1641968998851111
0.16419689988511113
0.16419689988511113
0.16419689988511113
0.16419689988511113
0.16419689988511108
0.16419689988511108
0.16419689988511105
0.164196899885111
0.16419689988511096
0.16419689988511096


0.1641968998851102
0.16419689988511021
0.16419689988511021
0.1641968998851102
0.1641968998851102
0.1641968998851102
0.1641968998851102
0.16419689988511016
0.16419689988511016
0.16419689988511013
0.16419689988511016
0.16419689988511016
0.16419689988511016
0.16419689988511013
0.16419689988511016
0.16419689988511013
0.16419689988511013
0.1641968998851101
0.16419689988511008
0.16419689988511005
0.16419689988511005
0.16419689988511005
0.16419689988511002
0.16419689988511002
0.16419689988511002
0.16419689988511002
0.16419689988511
0.16419689988511
0.16419689988511
0.16419689988511
0.16419689988511002
0.16419689988511002
0.16419689988511002
0.16419689988511002
0.16419689988511002
0.16419689988511005
0.16419689988511002
0.16419689988511002
0.16419689988511002
0.16419689988511
0.16419689988511
0.16419689988511002
0.16419689988511002
0.16419689988511002
0.16419689988511005
0.16419689988511005
0.16419689988511005
0.16419689988511
0.16419689988511005
0.16419689988511005
0.16419689988511005
0.16419

0.1641968998851099
0.1641968998851099
0.16419689988510994
0.1641968998851099
0.16419689988510994
0.1641968998851099
0.16419689988510985
0.16419689988510988
0.16419689988510988
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.1641968998851099
0.16419689988510994
0.16419689988510994
0.16419689988510994
0.16419689988511
0.16419689988511
0.16419689988511
0.16419689988511
0.16419689988510996
0.16419689988511002
0.16419689988511002
0.16419689988511002
0.16419689988510994
0.16419689988510996
0.16419689988510996
0.16419689988510994
0.1641968998851099
0.1641968998851099
0.16419689988510988
0.16419689988510985
0.16419689988510985
0.16419689988510985
0.16419689988510985
0.16419689988510985
0.16419689988510988

0.16419689988511174
0.1641968998851118
0.16419689988511185
0.16419689988511185
0.16419689988511185
0.16419689988511185
0.16419689988511185
0.16419689988511185
0.16419689988511185
0.16419689988511185
0.16419689988511182
0.1641968998851118
0.16419689988511177
0.16419689988511182
0.1641968998851118
0.1641968998851118
0.1641968998851118
0.1641968998851118
0.1641968998851118
0.1641968998851118
0.16419689988511182
0.16419689988511182
0.16419689988511182
0.16419689988511182
0.1641968998851118
0.16419689988511182
0.16419689988511185
0.16419689988511185
0.16419689988511188
0.16419689988511188
0.1641968998851119
0.16419689988511194
0.16419689988511196
0.164196899885112
0.16419689988511205
0.16419689988511207
0.16419689988511207
0.16419689988511216
0.16419689988511213
0.16419689988511216
0.1641968998851122
0.16419689988511227
0.16419689988511232
0.16419689988511238
0.16419689988511235
0.16419689988511238
0.16419689988511235
0.1641968998851124
0.16419689988511244
0.16419689988511246
0.164196899885

0.16419689988511435
0.16419689988511424
0.16419689988511432
0.1641968998851143
0.1641968998851143
0.16419689988511435
0.16419689988511432
0.16419689988511435
0.16419689988511435
0.16419689988511438
0.16419689988511438
0.1641968998851144
0.16419689988511438
0.1641968998851144
0.16419689988511435
0.16419689988511432
0.16419689988511438
0.1641968998851144
0.16419689988511438
0.16419689988511435
0.16419689988511435
0.16419689988511438
0.1641968998851144
0.16419689988511443
0.1641968998851144
0.1641968998851144
0.16419689988511446
0.16419689988511446
0.16419689988511446
0.16419689988511443
0.1641968998851144
0.16419689988511443
0.16419689988511443
0.16419689988511443
0.16419689988511446
0.1641968998851145
0.1641968998851144
0.1641968998851145
0.16419689988511446
0.1641968998851144
0.16419689988511446
0.16419689988511446
0.16419689988511446
0.16419689988511446
0.1641968998851145
0.1641968998851145
0.1641968998851145
0.16419689988511452
0.1641968998851145
0.16419689988511454
0.164196899885114

(array([298,  29, 174, 207, 149, 262,   7, 273, 318, 130, 183, 310,  76,
        128, 216, 154, 236, 120,  12, 304, 254, 342, 164,  79, 178,  74,
        330, 160, 295,  66,  69,  68, 352, 154, 183, 215, 167,  72, 117,
        174,  66, 220, 213, 247, 276, 240, 307, 288, 248, 247, 314,  25,
         20, 172,  42, 174, 291, 187,  47,  92, 157, 188, 308,  42,  35,
        200, 146, 329, 238, 326, 104,  68, 110, 269, 139,  19,  68, 221,
         11,  63, 117,  20, 168, 350,  83,  22, 316, 193, 171, 291, 340,
         93, 304, 112, 201, 125, 310, 250, 193, 351, 139, 117, 124, 211,
          4,  49, 353, 229, 186, 330, 220, 307, 125, 160, 225, 325, 322,
         10, 333, 131, 201, 339, 190, 187, 274, 273,   1, 247, 148, 220,
        356,  42, 114, 186, 245,  54,  37, 150, 286, 359, 153,   2,  94,
        174, 239, 183, 197,  16, 174, 335, 158, 197, 237, 269, 231, 302,
        352,   5,  63, 132, 203, 287,  69,  14,  38,  42,   1, 323, 273,
        298, 289, 324,  74, 247, 149, 329,  60, 223

In [267]:
print(X)

[[ 0.02978757  0.09347765 -0.00744489 ...  0.00369449 -0.02438425
   0.01137773]
 [-0.1260884  -0.16199732 -0.17945492 ... -0.13937549 -0.15643172
  -0.13295145]
 [ 0.05663541 -0.00136764  0.05563055 ...  0.01997001  0.09394415
   0.02955906]]
